server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///email
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    protocol: smtp
    host: smtp.sina.cn
    username: miniblackwang@sina.cn
    password: wywl123.!

dubbo:
  application:
    name: email_user_service
  registry:
    address: zookeeper://192.168.252.188:2181
  protocol:
    port: -1